### ISSUE TITLE
Published secure-json-parse includes .npmignore which excludes library during rush deploy

### ISSUE THREAD

**Issue by hfahlbusch** [fastify/secure-json-parse#23]
## 🐛 Bug Report
The pushed secure-json-parse node library 2.3.0 contains the .npmignore file which is preventing from integrating the library into a deployment that is evaluating npmignores. The `index.js` is then ignored by the contained file patterns:
`*
!lib/**
!.npmignore`

## To Reproduce
- install library into own project
- bundle own project including installed node_modules with an npmignore aware tool (rush deploy)
- resulting deploy artifact only includes .npmignore file and exludes the index.js

## Expected behavior
installed library should not contain .npmignore or should not ignore index.js so it can be repackaged.
Maybe an easy solution would be to exlude npmignore from published library.

## Your Environment
- *node version*: 12LTS
- *fastify version*: =2.3.0
- *os*: Mac, Linux
- aws cdk & rush monorepo

**Comment by Fdawgs** [comment]
@hfahlbusch, did 2.3.1 fix this for you?

**Comment by hfahlbusch** [comment]
@Fdawgs Yes, thanks a lot for the quick fix! Sorry, for the late reply. 
This allowed us to remove an "ugly" workaround in the build system.
