### ISSUE TITLE
json deserialize takes a lot of time.

### ISSUE THREAD

**Issue by zegulas** [fastify/secure-json-parse#33]
## 🐛 Bug Report

This is a simple case of using the npm package "@elastic/elasticsearch": "7.12.0", on using the DEBUG=* flag for loopback4, it shows that the deserialize json step takes the longest time, it even came up in the flamegraph as the most time consuming part of the entire operation to query and give back the response.

## To Reproduce

```js
const esResult = await this.ELASTICSEARCH_CLIENT.search({
        index: indice,
        body: temp,
        size: pageSize,
        from: startFrom,
        request_cache: true
});
```

## Expected behavior

The actual es query takes only a couple of ms, but the deserializing step takes 100+ms, why is the deserializing step becoming a bottleneck here, where the returned json is also just a couple of lines (less than 50 lines and less than 1000 characters), this brings down the entire response time of the api endpoint.

Paste the results here:
![image](https://user-images.githubusercontent.com/1142374/116971380-17ab9900-acd7-11eb-93c1-cfdeb865e9eb.png)

## Your Environment
node version: 14
@elastic/elasticsearch version: >=7.12.0
os: Mac

**Comment by mcollina** [comment]
It's totally true! However:

a. JSON deserializing is _not safe_ by default, as the resulting objects can be used as a vehicle for prototype pollution attacks.

b. The overhead introduced by this module is marginal vs the cost of `JSON.parse()`

As `JSON.parse()` is implemented natively, there is almost nothing we can do to improve on this problem.
